name: Apply Branch Protection

on:
  push:
    branches:
      - main

jobs:
  protect-release:
    runs-on: ubuntu-latest

    steps:
      - name: Apply branch protection
        env:
          GH_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          echo "Authenticating..."
          gh auth status

